# Generated by Django 4.1 on 2024-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_redactor_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
